[package]
name = "mbf_bridge"
description = "ModsBeforeFriday ADB Bridge"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[package.metadata.winresource]
ProductName = "ModsBeforeFriday ADB Bridge"
OriginalFilename = "mbf_bridge.exe"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
auto-launch = "0.5.0"
open = "5.1.3"
tao = "0.28.0"
tray-icon = { version = "0.20.0", default-features = false, features = [] }
tokio = { version = "1.37.0", features = ["full"] }
futures-util = "0.3.30"
image = { version = "0.25.1", default-features = false, features = ["png"] }
single-instance = "0.3.3"
reqwest = { version = "0.12.4", features = ["stream"] }
axum = { version = "0.8.1", features = ["macros", "ws"] }
tower-http = { version = "0.6.2", features = ["cors"] }
http = "1.2.0"
uuid = { version = "1.3", features = ["v4"] }
which = "7.0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
winreg = "0.55.0"

[build-dependencies]
winresource = "0.1"

[target."cfg(target_os = \"macos\")".dependencies]
core-foundation = "0.9"
